use_frameworks!

platform :ios, '8.0'

target 'NMCore_Example' do
  pod 'NMCore', :path => '../'

  target 'NMCore_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
