use_frameworks!

platform :ios, '8.0'

install! 'cocoapods', :deterministic_uuids => false

target 'NemoKit_Example' do
  pod 'NemoKit', :path => '../'

  target 'NemoKit_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
